/*
 * Bundles src/ into a single CommonJS main.js, which is what Obsidian loads.
 *
 * `obsidian` is external - the app provides it at runtime. Nothing else is,
 * and nothing else needs to be: this plugin has no dependencies at all, which
 * is part of why the same code runs unchanged on a phone.
 */

import esbuild from 'esbuild';

const watch = process.argv.includes('--watch');

const banner = `/*
 * Nextcloud Tasks for Obsidian - GENERATED by esbuild, do not edit.
 * Sources: https://github.com/JUNSKIx1/obsidian-nextcloud-tasks
 * MIT licensed. No bundled third-party code.
 */
`;

const options = {
  entryPoints: ['src/main.js'],
  bundle: true,
  outfile: 'main.js',
  format: 'cjs',
  platform: 'browser',
  target: 'es2018',
  external: ['obsidian', 'electron'],
  logLevel: 'info',
  sourcemap: false,
  treeShaking: true,
  // Not minified: the whole bundle is a few tens of KB of first-party code, and
  // a readable main.js is one less thing between a reviewer and the sources.
  minify: false,
  banner: { js: banner },
};

if (watch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
} else {
  await esbuild.build(options);
}
